BIN = ./node_modules/.bin
#SRC = $(wildcard src/*.coffee)
#LIB = $(SRC:src/%.coffee=lib/%.js)
REPORTER = dot

check: test

test: test-unit test-acceptance

test-mmm: build
	@$(BIN)/mocha -b specs

test: test-unit test-acceptance

test-unit:
	@NODE_ENV=test ./node_modules/.bin/mocha \
		--reporter $(REPORTER)

test-acceptance:
	@NODE_ENV=test ./node_modules/.bin/mocha \
		--reporter $(REPORTER) \
		--bail \
		tests/acceptance/*.js

test-cov: lib-cov
	@EXPRESS_COV=1 $(MAKE) test REPORTER=html-cov > coverage.html

#deploys working directory
deploy:
	@make test; \
  make deploy-git;

#deploys working to git deployment branch
deploy-git:
  @status=$$(git status --porcelain); \
		if test "x$${status}" = x; then \
			git branch -f deployment; \
			git push origin deployment; \
			echo "Done deploying to git deployment branch."; \
		else \
			git status; \
			echo "Error: cannot deploy. Working directory is dirty."; \
		fi

#lib-cov:
#	@jscoverage lib lib-cov
#
#benchmark:
#	@./support/bench

clean:
	rm -f coverage.html
#	rm -fr lib-cov

define release
  VERSION=`node -pe "require('./package.json').version"` && \
  NEXT_VERSION=`node -pe "require('semver').inc(\"$$VERSION\", '$(1)')"` && \
  node -e "\
		var j = require('./package.json');\
		j.version = \"$$NEXT_VERSION\";\
		var s = JSON.stringify(j, null, 2);\
		require('fs').writeFileSync('./package.json', s);" && \
  git commit -m "release $$NEXT_VERSION" -- package.json && \
  git tag "$$NEXT_VERSION" -m "release $$NEXT_VERSION"
endef

release-patch: build test
  @$(call release,patch)

release-minor: build test
  @$(call release,minor)

release-major: build test
  @$(call release,major)

publish:
  git push --tags origin HEAD:master
#  npm publish

#.PHONY: test test-unit test-acceptance benchmark clean deploy deploy-git
.PHONY: test test-unit test-acceptance clean deploy deploy-git
